### ISSUE TITLE
Linux implementation

### ISSUE THREAD

**Issue by tarnh** [matan2050/TFMatcherCpp#2]
Dear Matan,

I found you through https://sites.google.com/site/turningfunctions/ !

I'm a looking for a _Linux_ Turning Function implementation. The pure C++ would probably work as well, but I can't compile a MSVCPP project.

Or would you recommend https://github.com/matan2050/TFMatcher more?

Kind regards

**Comment by matan2050** [comment]
Hi,

I didn't try compiling it in Linux, but it should be fairly simple, just a
few header and code files, no outside libraries used, perhaps STL, don't
remember.

If you're having trouble, keep me posted, I can try to help you.

Matan

**Comment by tarnh** [comment]
I'm not so skilled in writing Makefiles, so mine isn't yet working: https://pastebin.com/wSisCGyf

**Comment by matan2050** [comment]
added makefile for building under linux

**Comment by matan2050** [comment]
added makefile and changed file structure. should be able to build under linux. in the future I will use CMake for building this
